# Generated by Django 3.2.19 on 2023-07-06 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('CourierID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
                ('Surname', models.CharField(max_length=45)),
                ('Phone', models.CharField(max_length=45)),
                ('LicenseType', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('CurrencyID', models.IntegerField(primary_key=True, serialize=False)),
                ('ExchangeRate', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('DistrictID', models.IntegerField(primary_key=True, serialize=False)),
                ('DistrictName', models.CharField(max_length=45)),
                ('CoordinationX', models.PositiveIntegerField()),
                ('CoordinationY', models.PositiveIntegerField()),
                ('Population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('DonationID', models.IntegerField(primary_key=True, serialize=False)),
                ('DonationTime', models.DateTimeField()),
                ('DonationDeliveryTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('DonorID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=225)),
                ('Surname', models.CharField(max_length=225)),
                ('Phone', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('ItemID', models.IntegerField(primary_key=True, serialize=False)),
                ('ItemCategory', models.CharField(max_length=45)),
                ('Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsCompany',
            fields=[
                ('CompanyID', models.IntegerField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=45)),
                ('Phone', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('PurchaseID', models.IntegerField(primary_key=True, serialize=False)),
                ('TransactionCost', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('RequestID', models.IntegerField(primary_key=True, serialize=False)),
                ('RequestTime', models.DateTimeField()),
                ('CurrentStatus', models.CharField(max_length=45)),
                ('DeliveryTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SupplierID', models.IntegerField(primary_key=True, serialize=False)),
                ('SupplierName', models.CharField(max_length=45)),
                ('Phone', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('VehicleID', models.IntegerField(primary_key=True, serialize=False)),
                ('VehicleType', models.CharField(max_length=45)),
                ('Capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donation_has_Currency',
            fields=[
                ('DonationID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.donation')),
                ('Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('VictimID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=225)),
                ('Surname', models.CharField(max_length=225)),
                ('Address', models.CharField(max_length=225)),
                ('PhoneNumber', models.PositiveIntegerField()),
                ('DistrictID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='Request_Vehicle_Courier_Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryTime', models.DateTimeField()),
                ('CourierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courier')),
                ('RequestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.request')),
                ('VehicleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Request_has_LogisticsCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryTime', models.DateTimeField()),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.logisticscompany')),
                ('RequestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.request')),
            ],
        ),
        migrations.CreateModel(
            name='Request_has_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('RequestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.request')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='RequesterID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.victim'),
        ),
        migrations.CreateModel(
            name='Purchase_has_Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PurchaseTransactionID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchase')),
                ('SupplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_has_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('UnitItemCost', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('PurchaseTransactionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsCompany_has_Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CostOfOutsource', models.DecimalField(decimal_places=1, max_digits=4)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.logisticscompany')),
                ('DistrictID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='Donation_has_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('DonationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.donation')),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='DonatorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.donor'),
        ),
        migrations.AddField(
            model_name='donation',
            name='RequestID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.request'),
        ),
        migrations.AddConstraint(
            model_name='request_vehicle_courier_assignment',
            constraint=models.UniqueConstraint(fields=('RequestID', 'CourierID', 'VehicleID'), name='unique_request_courier_vehicle'),
        ),
        migrations.AddConstraint(
            model_name='request_has_logisticscompany',
            constraint=models.UniqueConstraint(fields=('CompanyID', 'RequestID'), name='unique_company_request'),
        ),
        migrations.AddConstraint(
            model_name='request_has_items',
            constraint=models.UniqueConstraint(fields=('RequestID', 'ItemID'), name='unique_request_item'),
        ),
        migrations.AddConstraint(
            model_name='purchase_has_items',
            constraint=models.UniqueConstraint(fields=('PurchaseTransactionID', 'ItemID'), name='unique_transaction_item'),
        ),
        migrations.AddConstraint(
            model_name='logisticscompany_has_districts',
            constraint=models.UniqueConstraint(fields=('CompanyID', 'DistrictID'), name='unique_company_district'),
        ),
        migrations.AddConstraint(
            model_name='donation_has_items',
            constraint=models.UniqueConstraint(fields=('DonationID', 'ItemID'), name='unique_donation_item'),
        ),
        migrations.AddField(
            model_name='donation_has_currency',
            name='CurrencyType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.currency'),
        ),
    ]
