# Generated by Django 3.2.19 on 2023-07-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='DonatorID',
            new_name='DonorID',
        ),
        migrations.AlterField(
            model_name='items',
            name='ItemID',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='victim',
            name='PhoneNumber',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
