# Generated by Django 3.2.19 on 2023-07-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230709_1233'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='request_vehicle_courier_assignment',
            name='unique_request_courier_vehicle',
        ),
    ]
