# Generated by Django 3.2.19 on 2023-07-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_request_vehicle_courier_assignment_unique_request_courier_vehicle'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='logisticscompany_has_districts',
            name='unique_company_district',
        ),
        migrations.RemoveConstraint(
            model_name='request_vehicle_courier_assignment',
            name='unique_request_courier_vehicle',
        ),
    ]
